### ISSUE TITLE
[BUG] instantiating classes and examining methods

### ISSUE THREAD

**Issue by AnthonyTheKoala** [modular/max#245]
## Bug Description
When on the jupyter interface one gets these errors
### Steps to Reproduce

**Instantiating numpy**

`import numpy as np`
_Unable to locate module numpy_

**Instantiating scipy BUT cannot find methods of the instantiated class**
```
import scipy as sp
dir(sp)
```

_Unknown declaration dir_

Thank you

Anthony of Sydney

**Comment by Mogball** [comment]
@AnthonyTheKoala in order to import numpy or scipy properly, you have to run in a cell beginning with `%%python`. Check out the `Matmul.ipynb` notebook for examples on how to import Python modules into Mojo code, like

```python
np = Python.import_module("numpy")
sp = Python.import_module("scipy")
builtins = Python.import_module("builtins")
dir = builtins.dir
builtins.print(dir(sp))
```

This prints

```
['LowLevelCallable', '__numpy_version__', '__version__', 'cluster', 'fft', 'fftpack', 'integrate', 'interpolate', 'io', 'linalg', 'misc', 'ndimage', 'odr', 'optimize', 'show_config', 'signal', 'sparse', 'spatial', 'special', 'stats', 'test']
```

A Mojo version of `dir` is not yet available.
