### ISSUE TITLE
[BUG] `Python.import_module("tensorflow")` is timing out the playground server

### ISSUE THREAD

**Issue by USSiamaboat** [modular/max#300]
### Bug description

When attempting to import TensorFlow in both Mojo and Python mode, the cell seems to run indefinitely. Allowing the cell to run for long enough sometimes results in an error and has resulted in a server restart in some cases as well.

Interestingly, there is a way to get a TensorFlow import to run. After a failed attempt to import in Mojo, importing in Python mode executes in a few seconds. Further, importing in Mojo changes from an extremely long execution time to an error after a failed attempt to import in Python mode.

UPDATE:
I found a method to get Tensorflow to import without going in Python mode, which simply involves importing in Mojo, stopping execution when it runs for too long, and continually rerunning the cell until there are no errors.

### Steps to reproduce

Regular cell (referred to as "importing in Mojo" in description):

```py
tf = Python.import_module("tensorflow")
```

Python mode:

```py
%%python
import tensorflow as tf
```

### System information

```shell
11:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod045093ed_d4fc_43e9_a421_493a54917f8b.slice/cri-containerd-df60c7da70eb381505784e2210a3598688aa0b80c4a48a37af90f9072138c214.scope
10:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod045093ed_d4fc_43e9_a421_493a54917f8b.slice/cri-containerd-df60c7da70eb381505784e2210a3598688aa0b80c4a48a37af90f9072138c214.scope
9:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod045093ed_d4fc_43e9_a421_493a54917f8b.slice/cri-containerd-df60c7da70eb381505784e2210a3598688aa0b80c4a48a37af90f9072138c214.scope
8:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod045093ed_d4fc_43e9_a421_493a54917f8b.slice/cri-containerd-df60c7da70eb381505784e2210a3598688aa0b80c4a48a37af90f9072138c214.scope
7:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod045093ed_d4fc_43e9_a421_493a54917f8b.slice/cri-containerd-df60c7da70eb381505784e2210a3598688aa0b80c4a48a37af90f9072138c214.scope
6:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod045093ed_d4fc_43e9_a421_493a54917f8b.slice/cri-containerd-df60c7da70eb381505784e2210a3598688aa0b80c4a48a37af90f9072138c214.scope
5:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod045093ed_d4fc_43e9_a421_493a54917f8b.slice/cri-containerd-df60c7da70eb381505784e2210a3598688aa0b80c4a48a37af90f9072138c214.scope
4:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod045093ed_d4fc_43e9_a421_493a54917f8b.slice/cri-containerd-df60c7da70eb381505784e2210a3598688aa0b80c4a48a37af90f9072138c214.scope
3:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod045093ed_d4fc_43e9_a421_493a54917f8b.slice/cri-containerd-df60c7da70eb381505784e2210a3598688aa0b80c4a48a37af90f9072138c214.scope
2:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod045093ed_d4fc_43e9_a421_493a54917f8b.slice/cri-containerd-df60c7da70eb381505784e2210a3598688aa0b80c4a48a37af90f9072138c214.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod045093ed_d4fc_43e9_a421_493a54917f8b.slice/cri-containerd-df60c7da70eb381505784e2210a3598688aa0b80c4a48a37af90f9072138c214.scope
0::/
```

**Comment by Mogball** [comment]
@liamstewart

**Comment by Mogball** [comment]
@walter-erquinigo @River707 @stumpOS FYI

**Comment by River707** [comment]
Thanks a lot for the report! We discussed this a bit, but unfortunately decided to just remove tensorflow and related packages from the playground environment. Outside of configuration complications, there were a few other cost related reasons. Please take a look at the recent changelog for more details: https://docs.modular.com/mojo/changelog.html#removed. We may decide to reinclude it in the playground in the future, but for now it will be unavailable.

**Comment by JoeLoser** [comment]
@goldiegadde do you know why Linear reopened this GitHub issue?
